"""Registry-backed metadata exposed by the ZymePage web catalog."""

from __future__ import annotations

from typing import Any

from zymeforge.engineer.mutate import MODELS as MUTATION_MODEL_PLUGINS
from zymeforge.function import MODEL_PLUGINS
from zymeforge.model_hub import MODEL_ASSETS

REGISTRY_GROUPS = (
    {
        "id": "reaction-mining",
        "label": "Reaction Mining",
        "registries": (
            "reaction_database",
            "reaction_encoder",
            "reaction_search",
            "reaction2ec",
            "reaction2enzyme",
            "substrate2enzyme",
        ),
        "intro": (
            "Start from substrates, products, reaction SMILES, EC numbers, or names "
            "and retrieve enzyme candidates."
        ),
    },
    {
        "id": "mining-model-hub",
        "label": "Mining Model Hub",
        "registries": ("model_asset",),
        "intro": (
            "Discover official sequence, structure, text, and reaction mining assets with "
            "explicit compatibility status."
        ),
    },
    {
        "id": "sequence-search",
        "label": "Sequence Search",
        "registries": ("sequence_search",),
        "intro": (
            "Search sequence space with alignment, profile, and protein language model evidence."
        ),
    },
    {
        "id": "structure-search",
        "label": "Structure Search",
        "registries": (
            "structure_search",
            "active_site_search",
            "structure_comparison",
            "active_site_analysis",
            "ligand_analysis",
        ),
        "intro": (
            "Compare global folds and local catalytic geometry to recover remote enzyme "
            "relationships."
        ),
    },
    {
        "id": "function-prediction",
        "label": "Function Prediction",
        "registries": (
            "function_predictor",
            "substrate_compatibility",
            "kinetics_predictor",
            "stability_predictor",
            "ph_predictor",
            "solubility_predictor",
            "localization_predictor",
            "expression_predictor",
            "cofactor_predictor",
            "developability_predictor",
            "docking",
        ),
        "intro": (
            "Profile EC function, catalytic sites, substrate compatibility, kinetics, "
            "stability, and developability."
        ),
    },
    {
        "id": "structure-prediction",
        "label": "Structure Prediction",
        "registries": ("structure_predictor", "structure_quality"),
        "intro": (
            "Generate protein and complex structures for pocket inspection, docking, "
            "and consistency checks."
        ),
    },
    {
        "id": "engineering",
        "label": "Engineering",
        "registries": (
            "mutation_site_selector",
            "mutation_generator",
            "mutation_predictor",
            "mutation_optimizer",
            "design_model",
        ),
        "intro": (
            "Move from a selected enzyme to targeted mutation optimization or sequence redesign."
        ),
    },
    {
        "id": "evidence-fusion",
        "label": "Evidence Fusion",
        "registries": ("evidence_provider", "score_calibrator", "fusion_model"),
        "intro": (
            "Calibrate heterogeneous evidence into an explainable ZymeScore and candidate ranking."
        ),
    },
    {
        "id": "output",
        "label": "Output",
        "registries": ("output_writer",),
        "intro": (
            "Export candidates, evidence, score cards, and provenance for downstream analysis."
        ),
    },
)

REGISTRY_BY_CAPABILITY = {
    "prediction.function": "function_predictor",
    "active_site.search": "active_site_search",
    "prediction.substrate_compatibility": "substrate_compatibility",
    "prediction.kinetics": "kinetics_predictor",
    "prediction.stability": "stability_predictor",
    "prediction.ph": "ph_predictor",
    "prediction.solubility": "solubility_predictor",
    "prediction.localization": "localization_predictor",
    "prediction.expression": "expression_predictor",
    "prediction.cofactor": "cofactor_predictor",
    "prediction.developability": "developability_predictor",
    "prediction.docking": "docking",
    "engineering.mutation.predictor": "mutation_predictor",
    "engineering.redesign": "design_model",
}

TASK_LABELS = {
    "ec_prediction": "EC & function",
    "catalytic_site_prediction": "Catalytic site",
    "substrate_compatibility": "Substrate specificity",
    "kinetics_prediction": "Kinetics",
    "ph_prediction": "Optimal pH",
    "thermostability_prediction": "Thermostability",
    "solubility_prediction": "Solubility",
    "cofactor_prediction": "Cofactor specificity",
    "signal_peptide_prediction": "Developability",
    "transmembrane_prediction": "Developability",
    "localization_prediction": "Developability",
    "mutation_effect_prediction": "Mutation effects",
}

TASK_INTROS = {
    "reaction_mining": (
        "Search exact and similar reactions, infer EC classes, and rank enzyme candidates."
    ),
    "ec_prediction": "Predict EC numbers and enzyme function from a protein sequence.",
    "catalytic_site_prediction": "Identify residues and local geometry that support catalysis.",
    "substrate_compatibility": "Estimate whether a candidate enzyme can accept a target substrate.",
    "kinetics_prediction": "Estimate catalytic parameters for an enzyme-substrate pair.",
    "ph_prediction": "Predict the pH optimum for enzyme activity.",
    "thermostability_prediction": "Estimate melting temperature or thermostability probability.",
    "solubility_prediction": "Estimate whether a protein is likely to remain soluble.",
    "cofactor_prediction": "Predict cofactor preference such as NAD, NADP, or FAD.",
    "signal_peptide_prediction": "Detect signal peptides and likely cleavage sites.",
    "transmembrane_prediction": "Detect transmembrane regions and topology.",
    "localization_prediction": "Predict cellular localization for developability triage.",
    "mutation_effect_prediction": "Estimate stability and fitness effects of a proposed mutation.",
}

WORKFLOW_TOOLS = (
    {
        "id": "substrate-to-enzyme--mining",
        "name": "Substrate-to-Enzyme Mining",
        "plugin": "substrate_discovery",
        "version": "workflow-1.0",
        "task": "reaction_mining",
        "category": "Reaction mining",
        "introduction": ("Resolve SMILES, InChI, InChIKey, or names and retrieve linked enzymes."),
        "description": (
            "Runs the configured substrate-to-enzyme provider and returns normalized "
            "candidate, EC, reaction, confidence, source, and provenance fields."
        ),
        "role": "primary",
        "runtime": "zymeforge-unified",
        "inputs": ["query"],
        "outputs": ["candidate_enzymes", "predicted_ec", "confidence", "provenance"],
        "capability": "substrate.to_enzyme",
        "registry": "substrate2enzyme",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "workflow",
        "endpoint": "/api/substrates/mine",
    },
    {
        "id": "reaction-to-enzyme--mining",
        "name": "Reaction-to-Enzyme Mining",
        "plugin": "reaction_mining",
        "version": "workflow-1.0",
        "task": "reaction_mining",
        "category": "Reaction mining",
        "introduction": TASK_INTROS["reaction_mining"],
        "description": (
            "Runs the ZymeForge reaction standardizer, exact search, similarity search, "
            "reaction-to-EC, direct reaction-to-enzyme retrieval, and evidence fusion workflow."
        ),
        "role": "primary",
        "runtime": "zymeforge-unified",
        "inputs": ["reaction"],
        "outputs": ["ranked_candidates", "evidence", "zyme_score"],
        "capability": "reaction.to_enzyme",
        "registry": "reaction2enzyme",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "workflow",
        "endpoint": "/api/reactions/mine",
    },
)

REACTION_PROVIDER_TOOLS = (
    {
        "id": "mcsa--catalytic-templates",
        "name": "M-CSA Catalytic Templates",
        "plugin": "mcsa_templates",
        "version": "ingestion-1.0",
        "task": "catalytic_template_ingestion",
        "category": "Reaction mining",
        "introduction": "Load catalytic residues, roles, mechanisms, EC, PDB, and UniProt links.",
        "description": "Versioned M-CSA evidence with source checksum and grouped site templates.",
        "role": "database",
        "runtime": "zymeforge-unified",
        "inputs": ["mcsa_residue_csv"],
        "outputs": ["catalytic_residue_templates"],
        "capability": "database.reaction",
        "registry": "reaction_database",
        "requires_gpu": False,
        "citation": "M-CSA",
        "license": None,
        "available": True,
        "kind": "database",
        "endpoint": None,
    },
    {
        "id": "rhea--reaction-database",
        "name": "Rhea Reaction Database",
        "plugin": "rhea_tsv",
        "version": "ingestion-1.0",
        "task": "reaction_database_ingestion",
        "category": "Reaction mining",
        "introduction": "Load versioned Rhea reaction exports with EC and UniProt links.",
        "description": (
            "Preserves source version, checksum, row provenance, and normalized cross-links."
        ),
        "role": "database",
        "runtime": "zymeforge-unified",
        "inputs": ["versioned_rhea_tsv"],
        "outputs": ["reaction_database_snapshot"],
        "capability": "database.reaction",
        "registry": "reaction_database",
        "requires_gpu": False,
        "citation": "Rhea",
        "license": "CC BY 4.0",
        "available": True,
        "kind": "database",
        "endpoint": None,
    },
    {
        "id": "enzymemap--reaction-database",
        "name": "EnzymeMap Reaction Database",
        "plugin": "enzymemap",
        "version": "ingestion-1.0",
        "task": "reaction_database_ingestion",
        "category": "Reaction mining",
        "introduction": "Load standardized and atom-mapped EnzymeMap reaction tables.",
        "description": (
            "Auto-detects published CSV/TSV fields and records versioned checksum provenance."
        ),
        "role": "database",
        "runtime": "zymeforge-unified",
        "inputs": ["enzymemap_csv_or_tsv"],
        "outputs": ["reaction_database_snapshot"],
        "capability": "database.reaction",
        "registry": "reaction_database",
        "requires_gpu": False,
        "citation": "EnzymeMap",
        "license": None,
        "available": True,
        "kind": "database",
        "endpoint": None,
    },
    {
        "id": "local-exact--reaction-search",
        "name": "Exact Reaction Search",
        "plugin": "local_exact",
        "version": "1.0.0",
        "task": "reaction_search",
        "category": "Reaction mining",
        "introduction": "Resolve exact normalized reactions to annotated enzyme records.",
        "description": "The runnable local baseline behind the exact-reaction Harness route.",
        "role": "retrieval",
        "runtime": "zymeforge-unified",
        "inputs": ["normalized_reaction"],
        "outputs": ["reaction_hits", "candidate_enzymes"],
        "capability": "reaction.search",
        "registry": "reaction_search",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "provider",
        "endpoint": "/api/reactions/mine",
    },
    {
        "id": "reaction-similarity--search",
        "name": "Reaction Similarity Search",
        "plugin": "local_ngram_similarity",
        "version": "1.0.0",
        "task": "reaction_search",
        "category": "Reaction mining",
        "introduction": "Retrieve chemically related reaction records before enzyme expansion.",
        "description": (
            "Runnable lexical baseline with a stable route for DRFP/RXNFP/CGR providers."
        ),
        "role": "retrieval",
        "runtime": "zymeforge-unified",
        "inputs": ["normalized_reaction"],
        "outputs": ["reaction_hits", "candidate_enzymes"],
        "capability": "reaction.search",
        "registry": "reaction_search",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "provider",
        "endpoint": "/api/reactions/mine",
    },
    {
        "id": "catalog--reaction2ec",
        "name": "Reaction-to-EC",
        "plugin": "catalog_r2ec",
        "version": "1.0.0",
        "task": "reaction_to_ec",
        "category": "Reaction mining",
        "introduction": "Infer candidate EC classes from annotated related reactions.",
        "description": (
            "Runnable catalog baseline and extension point for learned reaction-to-EC models."
        ),
        "role": "prediction",
        "runtime": "zymeforge-unified",
        "inputs": ["normalized_reaction"],
        "outputs": ["ec_hits"],
        "capability": "reaction.to_ec",
        "registry": "reaction2ec",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "provider",
        "endpoint": "/api/reactions/mine",
    },
    {
        "id": "catalog--reaction2enzyme",
        "name": "Direct Reaction-to-Enzyme",
        "plugin": "catalog_r2enzyme",
        "version": "1.0.0",
        "task": "reaction_to_enzyme",
        "category": "Reaction mining",
        "introduction": "Retrieve proteins directly from reaction-conditioned evidence.",
        "description": "Runnable catalog baseline and extension point for CLIP-style retrieval.",
        "role": "retrieval",
        "runtime": "zymeforge-unified",
        "inputs": ["normalized_reaction", "protein_database"],
        "outputs": ["protein_hits"],
        "capability": "reaction.to_enzyme",
        "registry": "reaction2enzyme",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "provider",
        "endpoint": "/api/reactions/mine",
    },
)

SIMILARITY_TOOLS = (
    {
        "id": "mmseqs2--sequence-search",
        "name": "MMseqs2 Sequence Search",
        "plugin": "mmseqs2",
        "version": "cli-wrapper-1.0",
        "task": "protein_similarity",
        "category": "Sequence search",
        "introduction": (
            "Run high-throughput sequence alignment against a configured protein database."
        ),
        "description": (
            "Returns identity, query/target coverage, E-value, bit score, and alignment length."
        ),
        "role": "primary",
        "runtime": "external-binary",
        "inputs": ["sequence", "protein_database"],
        "outputs": ["similarity_hits"],
        "capability": "sequence.search",
        "registry": "sequence_search",
        "requires_gpu": False,
        "citation": "MMseqs2",
        "license": "GPL-3.0",
        "available": True,
        "kind": "retrieval",
        "endpoint": "/api/similarity/search",
    },
    {
        "id": "phmmer--sequence-search",
        "name": "phmmer Sequence Search",
        "plugin": "phmmer",
        "version": "cli-wrapper-1.0",
        "task": "protein_similarity",
        "category": "Sequence search",
        "introduction": "Search protein sequences with HMMER profile-HMM scoring.",
        "description": (
            "Parses domain-table output while retaining native E-values, scores, and coverage."
        ),
        "role": "primary",
        "runtime": "external-binary",
        "inputs": ["sequence", "protein_database"],
        "outputs": ["similarity_hits"],
        "capability": "sequence.search",
        "registry": "sequence_search",
        "requires_gpu": False,
        "citation": "HMMER",
        "license": "BSD-3-Clause",
        "available": False,
        "kind": "retrieval",
        "endpoint": "/api/similarity/search",
    },
    {
        "id": "hhsearch--profile-search",
        "name": "HHsearch Profile Search",
        "plugin": "hhsearch",
        "version": "cli-wrapper-1.0",
        "task": "remote_homology",
        "category": "Sequence search",
        "introduction": "Retrieve remote homologs by profile-profile comparison.",
        "description": (
            "Preserves HHsearch probability, E-value, P-value, score, and aligned columns."
        ),
        "role": "remote homology",
        "runtime": "external-binary",
        "inputs": ["a3m_or_hhm_profile", "hhsearch_database"],
        "outputs": ["similarity_hits"],
        "capability": "sequence.search",
        "registry": "sequence_search",
        "requires_gpu": False,
        "citation": "HH-suite",
        "license": "GPL-3.0",
        "available": False,
        "kind": "retrieval",
        "endpoint": None,
    },
    {
        "id": "esm2--similarity-retrieval",
        "name": "ESM-2 Retrieval",
        "plugin": "esm2_650m",
        "version": "1.0.0",
        "task": "protein_similarity",
        "category": "Sequence search",
        "introduction": "Retrieve proteins by ESM-2 sequence-semantic similarity.",
        "description": "Batched 650M embeddings, content cache, and Flat/HNSW retrieval.",
        "role": "primary",
        "runtime": "zymeforge-unified",
        "inputs": ["sequence"],
        "outputs": ["similarity_hits"],
        "capability": "sequence.search",
        "registry": "sequence_search",
        "requires_gpu": True,
        "citation": None,
        "license": "Apache-2.0",
        "available": False,
        "kind": "retrieval",
        "endpoint": "/api/similarity/search",
    },
    {
        "id": "saprot--similarity-retrieval",
        "name": "SaProt Retrieval",
        "plugin": "saprot_650m",
        "version": "1.0.0",
        "task": "protein_similarity",
        "category": "Structure search",
        "introduction": "Retrieve proteins using amino-acid and 3Di structural context.",
        "description": "Structure-aware SaProt embeddings with explicit structure provenance.",
        "role": "primary",
        "runtime": "zymeforge-unified",
        "inputs": ["sequence", "structural_tokens"],
        "outputs": ["similarity_hits"],
        "capability": "structure.search",
        "registry": "structure_search",
        "requires_gpu": True,
        "citation": None,
        "license": "Apache-2.0",
        "available": False,
        "kind": "retrieval",
        "endpoint": "/api/similarity/search",
    },
    {
        "id": "tmvec--similarity-retrieval",
        "name": "TM-Vec Retrieval",
        "plugin": "tmvec",
        "version": "1.0.0",
        "task": "protein_similarity",
        "category": "Sequence search",
        "introduction": "Find structural neighbors directly from protein sequence.",
        "description": "Published ProtT5-to-TM-Vec 512D structure-oriented retrieval.",
        "role": "primary",
        "runtime": "zymeforge-unified",
        "inputs": ["sequence"],
        "outputs": ["similarity_hits"],
        "capability": "sequence.search",
        "registry": "sequence_search",
        "requires_gpu": True,
        "citation": "10.1038/s41587-023-01917-2",
        "license": "BSD-3-Clause",
        "available": False,
        "kind": "retrieval",
        "endpoint": "/api/similarity/search",
    },
    {
        "id": "dhr--similarity-retrieval",
        "name": "DHR Retrieval",
        "plugin": "dhr",
        "version": "official-v2",
        "task": "protein_similarity",
        "category": "Sequence search",
        "introduction": "Retrieve remote homologs with dedicated asymmetric encoders.",
        "description": "Official DHR query encoder against target-encoder database vectors.",
        "role": "primary",
        "runtime": "zymeforge-unified",
        "inputs": ["sequence"],
        "outputs": ["similarity_hits"],
        "capability": "sequence.search",
        "registry": "sequence_search",
        "requires_gpu": True,
        "citation": "10.1038/s41587-024-02353-6",
        "license": "Apache-2.0",
        "available": False,
        "kind": "retrieval",
        "endpoint": "/api/similarity/search",
    },
    {
        "id": "protrek--similarity-retrieval",
        "name": "ProTrek Retrieval",
        "plugin": "protrek_650m",
        "version": "1.0.0",
        "task": "protein_similarity",
        "category": "Sequence search",
        "introduction": "Search proteins from sequence, structure, or natural-language text.",
        "description": "Tri-modal ProTrek shared-space retrieval with modality provenance.",
        "role": "primary",
        "runtime": "zymeforge-unified",
        "inputs": ["sequence", "structure_pdb", "text"],
        "outputs": ["similarity_hits"],
        "capability": "sequence.search",
        "registry": "sequence_search",
        "requires_gpu": True,
        "citation": None,
        "license": "MIT",
        "available": False,
        "kind": "retrieval",
        "endpoint": "/api/similarity/search",
    },
    {
        "id": "proteinmpnn--similarity-retrieval",
        "name": "ProteinMPNN Encoder Retrieval",
        "plugin": "proteinmpnn_encoder_experimental",
        "version": "1.0.0",
        "task": "protein_similarity",
        "category": "Structure search",
        "introduction": "Experimental retrieval from final ProteinMPNN backbone encoder states.",
        "description": "Chain-level, mean-pooled 128D backbone representation.",
        "role": "experimental",
        "runtime": "zymeforge-unified",
        "inputs": ["structure_pdb"],
        "outputs": ["similarity_hits"],
        "capability": "structure.search",
        "registry": "structure_search",
        "requires_gpu": True,
        "citation": None,
        "license": "Apache-2.0",
        "available": False,
        "kind": "retrieval",
        "endpoint": "/api/similarity/search",
    },
    {
        "id": "foldseek--similarity-retrieval",
        "name": "Foldseek Retrieval",
        "plugin": "foldseek",
        "version": "adapter-1.0",
        "task": "protein_similarity",
        "category": "Structure search",
        "introduction": "Search structures by 3Di and amino-acid local alignment.",
        "description": "Preserves identity, coverage, E-value, bit score, TM-scores, and lDDT.",
        "role": "primary",
        "runtime": "external-binary",
        "inputs": ["structure_pdb"],
        "outputs": ["similarity_hits"],
        "capability": "structure.search",
        "registry": "structure_search",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": False,
        "kind": "retrieval",
        "endpoint": "/api/similarity/search",
    },
    {
        "id": "dali--structural-validation",
        "name": "DALI Validation",
        "plugin": "dali",
        "version": "adapter-1.0",
        "task": "structural_validation",
        "category": "Structure search",
        "introduction": "Validate only the top retrieved structures using DALI Z-scores.",
        "description": "Returns Z-score, RMSD, aligned length, identity, and protein lengths.",
        "role": "validation",
        "runtime": "external-binary",
        "inputs": ["structure_pdb", "candidate_structures"],
        "outputs": ["dali_results"],
        "capability": "structure.search",
        "registry": "structure_search",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": False,
        "kind": "retrieval",
        "endpoint": "/api/similarity/search",
    },
)

ENGINEERING_TOOLS = (
    {
        "id": "foldx--mutation-stability",
        "name": "FoldX Mutation Stability",
        "plugin": "foldx",
        "version": "cli-wrapper-1.0",
        "task": "mutation_effect_prediction",
        "category": "Engineering",
        "introduction": "Estimate mutation ΔΔG with FoldX BuildModel.",
        "description": "Reads the FoldX difference output and preserves all native energy terms.",
        "role": "validation",
        "runtime": "external-binary",
        "inputs": ["protein_structure", "mutation"],
        "outputs": ["ddg", "energy_terms", "provenance"],
        "capability": "engineering.mutation.predictor",
        "registry": "mutation_predictor",
        "requires_gpu": False,
        "citation": "FoldX",
        "license": "FoldX terms apply",
        "available": False,
        "kind": "engineering",
        "endpoint": None,
    },
    {
        "id": "ligandmpnn--sequence-redesign",
        "name": "LigandMPNN Sequence Redesign",
        "plugin": "ligandmpnn",
        "version": "official-wrapper-1.0",
        "task": "sequence_redesign",
        "category": "Engineering",
        "introduction": (
            "Redesign a complete scaffold or selected pocket residues while preserving "
            "catalytic, ligand, membrane, and symmetry constraints."
        ),
        "description": (
            "One official wrapper for ProteinMPNN, LigandMPNN, SolubleMPNN, global-label "
            "membrane MPNN, per-residue membrane MPNN, score.py, and side-chain packing."
        ),
        "role": "primary",
        "runtime": "official-upstream",
        "inputs": ["structure_pdb", "model_type", "options"],
        "outputs": ["designed_sequences", "mutations", "scores", "provenance"],
        "capability": "engineering.redesign",
        "registry": "design_model",
        "requires_gpu": True,
        "citation": "Dauparas et al., LigandMPNN",
        "license": "MIT (upstream)",
        "available": False,
        "kind": "engineering",
        "endpoint": "/api/engineering/redesign",
    },
    {
        "id": "ligandmpnn--sequence-scoring",
        "name": "LigandMPNN Sequence Scoring",
        "plugin": "ligandmpnn",
        "version": "official-wrapper-1.0",
        "task": "sequence_scoring",
        "category": "Engineering",
        "introduction": (
            "Compare native, mutant, and designed sequences on matched backbones and "
            "ligand contexts."
        ),
        "description": (
            "Official score.py integration for autoregressive, single-AA, "
            "sequence-conditioned, and backbone-only scoring."
        ),
        "role": "validation",
        "runtime": "official-upstream",
        "inputs": ["structure_pdb", "sequence", "scoring_mode", "options"],
        "outputs": ["score", "per_residue_score", "provenance"],
        "capability": "engineering.redesign",
        "registry": "design_model",
        "requires_gpu": True,
        "citation": "Dauparas et al., LigandMPNN",
        "license": "MIT (upstream)",
        "available": False,
        "kind": "engineering",
        "endpoint": "/api/engineering/score",
    },
    {
        "id": "unzipro--mutation-prediction",
        "name": "unZipro Mutation Prediction",
        "plugin": "unzipro",
        "version": "official-wrapper-1.0",
        "task": "mutation_prediction",
        "category": "Engineering",
        "introduction": (
            "Prioritize function-oriented single substitutions for a selected protein."
        ),
        "description": (
            "Calls official unZipro inference, preserves its native probabilities and "
            "logits, and maps ranked predictions into ZymeForge candidates."
        ),
        "role": "primary",
        "runtime": "official-upstream",
        "inputs": ["sequence", "structure_pdb", "top_k"],
        "outputs": ["ranked_mutations", "native_scores", "provenance"],
        "capability": "engineering.mutation.predictor",
        "registry": "mutation_predictor",
        "requires_gpu": True,
        "citation": "unZipro",
        "license": None,
        "available": False,
        "kind": "engineering",
        "endpoint": "/api/engineering/mutations",
    },
)

STRUCTURE_TOOLS = (
    {
        "id": "fpocket--pocket-detection",
        "name": "fpocket Pocket Detection",
        "plugin": "fpocket",
        "version": "cli-wrapper-1.0",
        "task": "active_site_search",
        "category": "Structure search",
        "introduction": "Detect geometry-defined cavities for active-site screening.",
        "description": "Normalizes fpocket coordinate outputs as ranked pocket predictions.",
        "role": "pocket detection",
        "runtime": "external-binary",
        "inputs": ["protein_structure"],
        "outputs": ["pocket_predictions"],
        "capability": "active_site.search",
        "registry": "active_site_search",
        "requires_gpu": False,
        "citation": "fpocket",
        "license": "MIT",
        "available": False,
        "kind": "structure",
        "endpoint": None,
    },
    {
        "id": "p2rank--pocket-detection",
        "name": "P2Rank Pocket Detection",
        "plugin": "p2rank",
        "version": "cli-wrapper-1.0",
        "task": "active_site_search",
        "category": "Structure search",
        "introduction": "Predict ligand-binding pockets with P2Rank.",
        "description": "Preserves native rank, score, center, residues, and provider metadata.",
        "role": "pocket detection",
        "runtime": "external-binary",
        "inputs": ["protein_structure"],
        "outputs": ["pocket_predictions"],
        "capability": "active_site.search",
        "registry": "active_site_search",
        "requires_gpu": False,
        "citation": "P2Rank",
        "license": "MIT",
        "available": False,
        "kind": "structure",
        "endpoint": None,
    },
    {
        "id": "pocketmatch--site-comparison",
        "name": "PocketMatch Site Comparison",
        "plugin": "pocketmatch",
        "version": "cli-wrapper-1.0",
        "task": "active_site_search",
        "category": "Structure search",
        "introduction": "Compare local binding pockets independently of global fold.",
        "description": "Retains PocketMatch PMS scores as separate local-site evidence.",
        "role": "local comparison",
        "runtime": "external-binary",
        "inputs": ["query_pocket", "target_pocket"],
        "outputs": ["pocket_similarity"],
        "capability": "active_site.search",
        "registry": "active_site_search",
        "requires_gpu": False,
        "citation": "PocketMatch",
        "license": None,
        "available": False,
        "kind": "structure",
        "endpoint": None,
    },
    {
        "id": "boltz2--structure-prediction",
        "name": "Boltz-2 Structure Prediction",
        "plugin": "boltz2",
        "version": "official-cli-wrapper-1.0",
        "task": "structure_prediction",
        "category": "Structure prediction",
        "introduction": "Predict proteins, complexes, and protein-ligand structures with Boltz-2.",
        "description": "Preserves confidence, complex confidence, affinity output, and provenance.",
        "role": "primary",
        "runtime": "official-upstream",
        "inputs": ["sequence", "ligand", "cofactors"],
        "outputs": ["structure", "plddt", "ptm", "iptm", "affinity"],
        "capability": "structure.predictor",
        "registry": "structure_predictor",
        "requires_gpu": True,
        "citation": "Boltz-2",
        "license": "MIT; model terms apply",
        "available": False,
        "kind": "structure",
        "endpoint": "/api/structures/predict",
    },
    {
        "id": "alphafold3--structure-prediction",
        "name": "AlphaFold 3 Local Prediction",
        "plugin": "alphafold3",
        "version": "official-local-wrapper-1.0",
        "task": "structure_prediction",
        "category": "Structure prediction",
        "introduction": "Local AF3 prediction for proteins, ligands, and nucleic acids.",
        "description": "Enabled only with legally provisioned local parameters and databases.",
        "role": "primary",
        "runtime": "official-upstream",
        "inputs": ["sequence", "ligand", "cofactors"],
        "outputs": ["structure", "plddt", "pae", "ptm", "iptm"],
        "capability": "structure.predictor",
        "registry": "structure_predictor",
        "requires_gpu": True,
        "citation": "Abramson et al., Nature 2024",
        "license": "AlphaFold 3 terms apply",
        "available": False,
        "kind": "structure",
        "endpoint": "/api/structures/predict",
    },
    {
        "id": "esmfold--structure-prediction",
        "name": "ESMFold Fast Screening",
        "plugin": "esmfold",
        "version": "fair-esm-wrapper-1.0",
        "task": "structure_prediction",
        "category": "Structure prediction",
        "introduction": "Fast single-protein prediction for large candidate screens.",
        "description": "Retains mean and per-residue pLDDT, pTM, runtime, and checkpoint hash.",
        "role": "screening",
        "runtime": "official-upstream",
        "inputs": ["sequence"],
        "outputs": ["structure", "mean_plddt", "per_residue_plddt", "ptm"],
        "capability": "structure.predictor",
        "registry": "structure_predictor",
        "requires_gpu": True,
        "citation": "Lin et al., Science 2023",
        "license": "MIT",
        "available": False,
        "kind": "structure",
        "endpoint": "/api/structures/predict",
    },
    {
        "id": "usalign--structure-comparison",
        "name": "US-align / TM-align Comparison",
        "plugin": "usalign",
        "version": "cli-wrapper-1.0",
        "task": "structure_comparison",
        "category": "Structure search",
        "introduction": "Validate global fold preservation with pairwise structural alignment.",
        "description": "Returns both normalized TM-scores, RMSD, aligned length, and identity.",
        "role": "validation",
        "runtime": "external-binary",
        "inputs": ["query_structure", "target_structure"],
        "outputs": ["tm_score", "rmsd", "aligned_length"],
        "capability": "structure.comparison",
        "registry": "structure_comparison",
        "requires_gpu": False,
        "citation": None,
        "license": None,
        "available": False,
        "kind": "structure",
        "endpoint": "/api/structures/compare",
    },
    {
        "id": "active-site--geometry-validation",
        "name": "Active-site Geometry Validation",
        "plugin": "active_site_geometry",
        "version": "1.0.0",
        "task": "active_site_validation",
        "category": "Structure search",
        "introduction": (
            "Compare catalytic residues and pocket geometry independently of global fold."
        ),
        "description": "Returns catalytic RMSD, distances, angles, conservation, and local pLDDT.",
        "role": "validation",
        "runtime": "zymeforge-unified",
        "inputs": ["query_structure", "reference_structure", "catalytic_residues"],
        "outputs": ["active_site_rmsd", "pocket_rmsd", "geometry"],
        "capability": "structure.active_site",
        "registry": "active_site_analysis",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "structure",
        "endpoint": "/api/structures/active-site",
    },
    {
        "id": "ligand--geometry-analysis",
        "name": "Ligand and Metal Geometry Analysis",
        "plugin": "ligand_geometry",
        "version": "1.0.0",
        "task": "ligand_analysis",
        "category": "Structure search",
        "introduction": "Inspect ligand contacts, clashes, hydrogen bonds, and metal coordination.",
        "description": "Keeps contact residues and external pocket-volume/BSA evidence separate.",
        "role": "validation",
        "runtime": "zymeforge-unified",
        "inputs": ["structure", "ligand_id"],
        "outputs": ["contacts", "clashes", "metal_geometry", "ligand_rmsd"],
        "capability": "structure.ligand_analysis",
        "registry": "ligand_analysis",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "structure",
        "endpoint": "/api/structures/ligand",
    },
    {
        "id": "molprobity--structure-quality",
        "name": "MolProbity Structure QC",
        "plugin": "molprobity",
        "version": "cli-wrapper-1.0",
        "task": "structure_quality",
        "category": "Structure prediction",
        "introduction": "Run mature structural quality checks after prediction.",
        "description": "Reports clashes, Ramachandran outliers, geometry errors, and chain issues.",
        "role": "validation",
        "runtime": "external-binary",
        "inputs": ["structure"],
        "outputs": ["clash_score", "ramachandran_outliers", "geometry_errors"],
        "capability": "structure.quality",
        "registry": "structure_quality",
        "requires_gpu": False,
        "citation": "MolProbity",
        "license": None,
        "available": False,
        "kind": "structure",
        "endpoint": "/api/structures/quality",
    },
)

EVIDENCE_TOOLS = (
    {
        "id": "platt--score-calibration",
        "name": "Platt Score Calibration",
        "plugin": "platt",
        "version": "1.0.0",
        "task": "score_calibration",
        "category": "Evidence fusion",
        "introduction": "Map provider-native scores to comparable probabilities.",
        "description": "Regularized logistic calibration with Brier score reporting.",
        "role": "calibration",
        "runtime": "zymeforge-unified",
        "inputs": ["raw_scores", "binary_labels"],
        "outputs": ["calibrated_probability", "calibration_report"],
        "capability": "evidence.calibrator",
        "registry": "score_calibrator",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "fusion",
        "endpoint": None,
    },
    {
        "id": "isotonic--score-calibration",
        "name": "Isotonic Score Calibration",
        "plugin": "isotonic",
        "version": "1.0.0",
        "task": "score_calibration",
        "category": "Evidence fusion",
        "introduction": "Learn a non-parametric monotonic score calibration.",
        "description": "Pool-adjacent-violators calibration with explicit thresholds and values.",
        "role": "calibration",
        "runtime": "zymeforge-unified",
        "inputs": ["raw_scores", "binary_labels"],
        "outputs": ["calibrated_probability", "calibration_report"],
        "capability": "evidence.calibrator",
        "registry": "score_calibrator",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "fusion",
        "endpoint": None,
    },
    {
        "id": "pareto--candidate-ranking",
        "name": "Pareto Candidate Ranking",
        "plugin": "pareto",
        "version": "1.0.0",
        "task": "candidate_ranking",
        "category": "Evidence fusion",
        "introduction": "Rank non-dominated candidates across conflicting objectives.",
        "description": (
            "Preserves multi-objective tradeoffs without forcing unlike scores together."
        ),
        "role": "ranking",
        "runtime": "zymeforge-unified",
        "inputs": ["candidate_objectives"],
        "outputs": ["pareto_fronts", "ranked_candidates"],
        "capability": "evidence.fusion",
        "registry": "fusion_model",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "fusion",
        "endpoint": None,
    },
    {
        "id": "logistic--evidence-ranking",
        "name": "Logistic Evidence Ranking",
        "plugin": "logistic_evidence_ranker",
        "version": "1.0.0",
        "task": "candidate_ranking",
        "category": "Evidence fusion",
        "introduction": "Fit a transparent learned ranking baseline on labeled candidates.",
        "description": "Reports calibrated score and per-feature contributions for each candidate.",
        "role": "learned ranking",
        "runtime": "zymeforge-unified",
        "inputs": ["calibrated_feature_matrix", "binary_labels"],
        "outputs": ["ranked_candidates", "feature_contributions"],
        "capability": "evidence.fusion",
        "registry": "fusion_model",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "fusion",
        "endpoint": None,
    },
    {
        "id": "weighted--evidence-fusion",
        "name": "Weighted Evidence Fusion",
        "plugin": "weighted_calibrated_mean",
        "version": "1.0.0",
        "task": "evidence_fusion",
        "category": "Evidence fusion",
        "introduction": "Combine calibrated evidence with explicit per-channel contributions.",
        "description": "Runnable transparent baseline used by the reaction-mining workflow.",
        "role": "primary",
        "runtime": "zymeforge-unified",
        "inputs": ["evidence_records"],
        "outputs": ["zyme_score", "confidence", "contributions"],
        "capability": "evidence.fusion",
        "registry": "fusion_model",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "fusion",
        "endpoint": "/api/reactions/mine",
    },
    {
        "id": "rrf--similarity-fusion",
        "name": "Reciprocal Rank Fusion",
        "plugin": "rrf",
        "version": "1.0.0",
        "task": "rank_fusion",
        "category": "Evidence fusion",
        "introduction": "Merge independent retrieval rankings without mixing native scores.",
        "description": "Optional RRF over canonicalized similarity hits.",
        "role": "consensus",
        "runtime": "zymeforge-unified",
        "inputs": ["similarity_rankings"],
        "outputs": ["merged_candidates", "rrf_score"],
        "capability": "evidence.fusion",
        "registry": "fusion_model",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "fusion",
        "endpoint": "/api/similarity/search",
    },
    {
        "id": "zymescore--candidate-ranking",
        "name": "ZymeScore Candidate Ranking",
        "plugin": "zymescore",
        "version": "1.0.0",
        "task": "candidate_ranking",
        "category": "Evidence fusion",
        "introduction": "Rank unified Candidates while preserving all source evidence.",
        "description": "Harness candidate-ranking tool using ZymeScore or available evidence.",
        "role": "ranking",
        "runtime": "zymeforge-unified",
        "inputs": ["candidates", "evidence"],
        "outputs": ["ranked_candidates"],
        "capability": "evidence.fusion",
        "registry": "fusion_model",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "fusion",
        "endpoint": "/api/harness/run",
    },
)

OUTPUT_TOOLS = (
    {
        "id": "harness--tool-health",
        "name": "Tool Availability Health",
        "plugin": "tool_health",
        "version": "1.0.0",
        "task": "operations",
        "category": "Output",
        "introduction": (
            "Inspect binaries, checkpoints, indexes, databases, licenses, and handlers."
        ),
        "description": (
            "Reports unavailable dependencies explicitly without producing fake results."
        ),
        "role": "operations",
        "runtime": "zymeforge-unified",
        "inputs": [],
        "outputs": ["tool_health_reports"],
        "capability": "output.writer",
        "registry": "output_writer",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "output",
        "endpoint": "/api/health/tools",
    },
    {
        "id": "json--output-writer",
        "name": "JSON Result Writer",
        "plugin": "json",
        "version": "1.0.0",
        "task": "output",
        "category": "Output",
        "introduction": "Write complete typed results and provenance as portable JSON.",
        "description": "Built-in output writer for workflows and APIs.",
        "role": "primary",
        "runtime": "zymeforge-unified",
        "inputs": ["result"],
        "outputs": ["json_file"],
        "capability": "output.writer",
        "registry": "output_writer",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "output",
        "endpoint": None,
    },
    {
        "id": "candidate-tsv--output-writer",
        "name": "Candidate TSV Writer",
        "plugin": "candidate_tsv",
        "version": "1.0.0",
        "task": "output",
        "category": "Output",
        "introduction": "Export flattened candidate tables for downstream analysis.",
        "description": "Built-in tab-separated candidate writer.",
        "role": "primary",
        "runtime": "zymeforge-unified",
        "inputs": ["candidate_rows"],
        "outputs": ["tsv_file"],
        "capability": "output.writer",
        "registry": "output_writer",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "output",
        "endpoint": None,
    },
    {
        "id": "harness--run-artifacts",
        "name": "Harness Run Artifacts",
        "plugin": "run_store",
        "version": "1.0.0",
        "task": "output",
        "category": "Output",
        "introduction": "Persist plans, tool results, candidates, provenance, and HTML reports.",
        "description": "Reproducible seven-artifact Harness run directory.",
        "role": "reporting",
        "runtime": "zymeforge-unified",
        "inputs": ["run_state"],
        "outputs": ["run_json", "candidates_csv", "provenance", "report_html"],
        "capability": "output.writer",
        "registry": "output_writer",
        "requires_gpu": False,
        "citation": None,
        "license": "Apache-2.0",
        "available": True,
        "kind": "output",
        "endpoint": "/api/harness/runs/{run_id}",
    },
)


def serialize_model_asset(asset: Any) -> dict[str, Any]:
    """Expose core Model Hub metadata without claiming that downloaded means runnable."""
    return {
        "id": f"model-asset--{asset.id.replace('_', '-')}",
        "name": asset.id.replace("_", " ").title(),
        "plugin": asset.provider,
        "version": asset.revision,
        "task": asset.tasks[0] if asset.tasks else "model_asset",
        "category": "Mining Model Hub",
        "introduction": asset.purpose,
        "description": asset.notes or asset.purpose,
        "role": asset.asset_type,
        "runtime": asset.compatibility,
        "inputs": list(asset.modalities),
        "outputs": list(asset.tasks),
        "capability": "model.asset",
        "registry": "model_asset",
        "requires_gpu": asset.asset_type == "model",
        "citation": asset.homepage,
        "license": None,
        # Static Pages cannot know whether a deployment has downloaded the asset.
        "available": False,
        "kind": "asset",
        "endpoint": asset.official_download or asset.homepage,
    }


def tool_id(model: type[Any]) -> str:
    """Return a stable URL identifier for a registered model/task pair."""
    return f"{model.spec.name}--{model.card.task}".replace("_", "-")


def serialize_model(model: type[Any]) -> dict[str, Any]:
    """Convert an adapter class into browser-safe catalog metadata."""
    card = model.card
    spec = model.spec
    return {
        "id": tool_id(model),
        "name": card.name,
        "plugin": spec.name,
        "version": spec.version,
        "task": card.task,
        "category": TASK_LABELS.get(card.task, card.task.replace("_", " ").title()),
        "description": spec.description,
        "introduction": TASK_INTROS.get(card.task, spec.description),
        "role": card.role,
        "runtime": card.runtime,
        "inputs": list(card.input_fields),
        "outputs": list(card.output_fields),
        "capability": spec.capability,
        "registry": REGISTRY_BY_CAPABILITY.get(spec.capability, spec.capability),
        "requires_gpu": spec.requires_gpu,
        "citation": spec.citation,
        "license": spec.license,
        "available": False,
        "kind": "model",
        "endpoint": f"/api/models/{tool_id(model)}/predict",
    }


def list_tools() -> list[dict[str, Any]]:
    """List every functional and mutation model registered by ZymeForge."""
    models = (*MODEL_PLUGINS, *MUTATION_MODEL_PLUGINS)
    return sorted(
        [
            *WORKFLOW_TOOLS,
            *REACTION_PROVIDER_TOOLS,
            *SIMILARITY_TOOLS,
            *ENGINEERING_TOOLS,
            *STRUCTURE_TOOLS,
            *EVIDENCE_TOOLS,
            *OUTPUT_TOOLS,
            *(serialize_model_asset(asset) for asset in MODEL_ASSETS),
            *(serialize_model(model) for model in models),
        ],
        key=lambda item: item["name"],
    )


def list_models() -> list[dict[str, Any]]:
    """List model adapters without workflow tools."""
    return [tool for tool in list_tools() if tool["kind"] == "model"]


def list_registry_groups() -> list[dict[str, Any]]:
    """Return Proto-style registry navigation with the currently registered tools."""
    tools = list_tools()
    groups: list[dict[str, Any]] = []
    for group in REGISTRY_GROUPS:
        registries = set(group["registries"])
        group_tools = [tool for tool in tools if tool["registry"] in registries]
        groups.append({**group, "tools": group_tools, "count": len(group_tools)})
    return groups


def get_tool(identifier: str) -> tuple[type[Any] | None, dict[str, Any]] | None:
    """Resolve a catalog item and its model adapter class."""
    for tool in list_tools():
        if tool["id"] == identifier:
            if tool["kind"] != "model":
                return None, tool
            for model in (*MODEL_PLUGINS, *MUTATION_MODEL_PLUGINS):
                if tool_id(model) == identifier:
                    return model, tool
    return None
